<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>False</UseWPF>
    <UseWindowsForms>True</UseWindowsForms>
    <StartupObject>Program</StartupObject>
    <ApplicationIcon>..\..\res\textures\legendarySword.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MouseKeyHook" Version="5.7.1" />
    <PackageReference Include="SkiaSharp" Version="3.119.0" />
    <PackageReference Include="System.Drawing.Common" Version="7.0.0" />
  </ItemGroup>

</Project>
